applications:
  - name: app
    type: web
    image: node:18
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - name: http
        containerPort: 3000
    env:
      - name: NODE_ENV
        value: production
    command: ["npm", "start"]
    replicas: 2
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"
    livenessProbe:
      httpGet:
        path: /health
        port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /health
        port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10
    startupProbe:
      httpGet:
        path: /health
        port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10